### ISSUE TITLE
how to give the click event for imageview?

### ISSUE THREAD

**Issue by ghost** [mollyIV/ChatHeads#1]
i have define the imageview  below `layoutInflater.inflate(R.layout.head, mFrameLayout);`  and also give the click event 
Here is my code:

` 

```
   Here is the place where you can inject whatever layout you want.
    layoutInflater.inflate(R.layout.head, mFrameLayout);

    ImageView img1 = (ImageView) findViewById(R.id.img1);

    img1.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            Toast.makeText(mContext,"Hi",Toast.LENGTH_LONG).show();
        }
    });
```

`

But it gives me error on img1.setOnclickListener.  Even i am not able to open keyboard if this service is running. 

error log

`

 Process: com.example.launchgest, PID: 14016
                                                                           java.lang.RuntimeException: Unable to start service com.example.launchgest.HeadService@420e1580 with Intent { cmp=com.example.launchgest/.HeadService }: java.lang.NullPointerException
                                                                               at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2924)
                                                                               at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                               at android.os.Looper.loop(Looper.java:193)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.NullPointerException
                                                                               at com.example.launchgest.HeadLayer.addToWindowManager(HeadLayer.java:53)
                                                                               at com.example.launchgest.HeadLayer.<init>(HeadLayer.java:30)
                                                                               at com.example.launchgest.HeadService.initHeadLayer(HeadService.java:48)
                                                                               at com.example.launchgest.HeadService.onStartCommand(HeadService.java:29)
                                                                               at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2907)
                                                                               at android.app.ActivityThread.access$2100(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                               at android.os.Looper.loop(Looper.java:193) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 

`
How can i solved that

**Comment by mollyIV** [comment]
Hi @rushank ,
so sorry for a late response. I took a look at that issue and found what's wrong with code posted above. Using widget as static ones is a bad idea. Basically you should handle all your widgets logic inside HeadLayer. So try to modify code in **HeadLayer** file to something like this:

```
mFloatingActionButton = (FloatingActionButton) rootView.findViewById(R.id.fab);
mFloatingActionButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Handle click
            }
        });
```

If you have another issue, just let me know. Cheers!
